# Generated by Django 5.2.1 on 2025-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('theatre', models.CharField(max_length=100)),
                ('show_timing', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('selected_seats', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
